# has_discussions: true
has_downloads: true
has_issues: false
# has_pages: false
has_projects: false
allow_squash_merge : false
allow_merge_commit : true
allow_rebase_merge : false
delete_branch_on_merge : true
has_wiki: false
is_template: false
